{{- if .Values.ingress.enabled -}}
{{- $fullName := include "app.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- if .Values.ingress.cors }}
    nginx.ingress.kubernetes.io/enable-cors: "true"
    {{- end }}
    {{- if .Values.ingress.phpfpm }}
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/backend-protocol: FCGI
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_clear_headers "Server";
    nginx.ingress.kubernetes.io/fastcgi-index: index.php
    nginx.ingress.kubernetes.io/fastcgi-params-configmap: {{ include "app.fullname" . }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
    {{- if .Values.ingress.ws }}
    nginx.org/proxy-connect-timeout: 30s
    nginx.org/proxy-read-timeout: 86400s
    nginx.org/proxy-send-timeout: 30s
    {{- end }}
    {{- if .Values.ingress.secureVpn }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "84.201.178.97/32"
    {{- end }}
spec:
  ingressClassName:  {{ .Values.ingress.className | quote }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }} 
{{- end }}
